services:
  alura-postgres:
    image: postgres
    container_name: alura-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alura
      POSTGRES_PASSWORD: alura1234
      POSTGRES_DB: alura-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data