services:
  alura-postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - 5431:5431
    environment:
      POSTGRES_USER: alura
      POSTGRES_PASSWORD: alura
      POSTGRES_DB: alura_db
    volumes:
      - ./postgres:/var/lib/postgresql/data